#
##ORIGINAL STRING TO COW CODE.DO credits are given at the end
##Modified by Casey Crisman-Cox for R, 16 June 2012
##NOTES: If  country==
##                                      Yemen and both YAR and YPR exist then it defaults to YAR
##                                              Germany and both GFR and GDR exist defaults to GFR
##                                              Vietnam and both DRV and RVN exist then defaults to RVN
##                                              Only use this file for post 1945
## UPDATE 19 September 2014: Moved Dominca before Dominican Republic 
stringr.to.cow<-function(country, year, data){
  require(stringr)
  ccode<- vector(length=length(country))
  if(class(country)=="factor"){
    cctry<-as.character(country)
    ccode<-cbind.data.frame(cctry, ccode, stringsAsFactors=FALSE)}else{
      ccode<-cbind.data.frame(country, ccode, stringsAsFactors=FALSE)
      colnames(ccode)[1]<-"cctry"
    }
  2 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("United States of America"))]
  2 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("United States"))]
  2 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("USA"))]
  20 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Canada"))]
  31 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Bahamas"))]
  31 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Bahamas, The"))]
  40 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Cuba"))]
  41 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Haiti"))]
  54 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Dominica"))]
  42 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Dominican Republic"))]
  42 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("DominRep"))]
  51 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Jamaica"))]
  52 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Trinidad and Tobago"))]
  52 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Trinidad"))]
  52 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Trinidad & Tobago"))]
  52 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Trinidad &Tobago"))]
  53 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Barbados"))]
  55 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Grenada"))]
  56 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("St. Lucia"))]
  56 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Saint Lucia"))]
  57 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("St. Vincent and the Grenadines"))]
  57 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Saint Vincent and the Grenadines"))]
  57 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("St. Vincent and Grenadines"))]
  57 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("St. Vincent & Grens."))]
  57 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("St. Vincent & Grenadines"))]
  57 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("St.Vincent & Grenadines"))]
  58 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Antigua & Barbuda"))]
  58 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Antigua and Barbuda"))]
  58 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Antigua"))]
  60 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("St. Kitts and Nevis"))]
  60 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Saint Kitts and Nevis"))]
  60 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("St. Kitts & Nevis"))]
  70 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Mexico"))]
  80 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Belize"))]
  90 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Guatemala"))]
  90 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Guatemal"))]
  91 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Honduras"))]
  92 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("El Salvador"))]
  92 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("ElSalvad"))]
  93 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Nicaragua"))]
  93 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Nicaragu"))]
  94 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Costa Rica"))]
  94 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("CostaRic"))]
  94 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("CostaRica"))]
  95 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Panama"))]
  100 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Colombia"))]
  101 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Venezuela"))]
  101 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Venezuel"))]
  101 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Venezuela, Rep. Bol."))]
  110 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Guyana"))]
  115 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Suriname"))]
  130 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Ecuador"))]
  135 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Peru"))]
  140 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Brazil"))]
  145 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Bolivia"))]
  150 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Paraguay"))]
  155 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Chile"))]
  160 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Argentina"))]
  160 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Argentin"))]
  165 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Uruguay"))]
  200 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("United Kingdom"))]
  200 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("UKG"))]
  200 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("UK"))]
  205 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Ireland"))]
  210 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Netherlands"))]
  210 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Netherla"))]
  211 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Belgium"))]
  212 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Luxembourg"))]
  212 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Luxembou"))]
  220 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("France"))]
  221 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Monaco"))]
  223 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Liechtenstein"))]
  225 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Switzerland"))]
  225 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Switzerl"))]
  230 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Spain"))]
  232 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Andorra"))]
  235 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Portugal"))]
  255 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Germany")) & year>=1991]
  
  260 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("German Federal Republic"))]
  260 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Germany, West"))]
  260 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("West Germany"))]
  260 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Germany")) & year<=1990]
  
  265 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("German Democratic Republic"))]
  265 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("GERMAN DEM. REP."))]
  265 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Germany, East"))]
  290 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Poland"))]
  305 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Austria"))]
  310 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Hungary"))]
  315 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Czechoslovakia"))]
  316 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Czech Republic"))]
  316 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("czechrep"))]
  317 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Slovakia"))]
  317 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Slovak Republic"))]
  325 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Italy"))]
  331 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("San Marino"))]
  338 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Malta"))]
  339 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Albania"))]
  341 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Montenegro"))]
  343 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Macedonia"))]
  343 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Macedonia, Former Yugoslav Republic"))]
  344 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Croatia"))]
  345 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yugoslavia"))]
  345 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Serbia"))]
  345 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Serbia and Montenegro"))]
  345 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Serbia and Montenegro, Former"))]
  346 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Bosnia and Herzegovina"))]
  346 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Bosnia"))]
  346 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Bosnia-Herzegovina"))]
  346 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Bosnia & Herzegovina"))]
  347-> ccode$ccode[str_detect(ccode$cctry, ignore.case("Kosovo"))]
  349 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Slovenia"))]
  350 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Greece"))]
  352 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Cyprus"))]
  352 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Cyprus (Greek)"))]
  355 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Bulgaria"))]
  359 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Moldova"))]
  698 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Oman"))]
  360 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Romania"))]
  365 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Russia"))]
  365 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("USSR"))]
  365 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Soviet Union"))]
  366 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Estonia"))]
  367 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Latvia"))]
  368 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Lithuania"))]
  369 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Ukraine"))]
  370 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Belarus"))]
  371 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Armenia"))]
  372 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Georgia"))]
  373 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Azerbaijan"))]
  375 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Finland"))]
  380 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Sweden"))]
  385 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Norway"))]
  390 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Denmark"))]
  390 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Denmark"))]
  395 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Iceland"))]
  402 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Cape Verde"))]
  403 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Sao Tome and Principe"))]
  403 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Sao Tome & Principe"))]
  438 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Guinea"))]
  404 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Guinea-Bissau"))]
  404 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Guinea Bissau"))]
  411 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Equatorial Guinea"))]
  420 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Gambia"))]
  420 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Gambia, The"))]
  432 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Mali"))]
  433 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Senegal"))]
  434 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Benin"))]
  435 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Mauritania"))]
  435 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Mauritan"))]
  436 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Niger"))]
  437 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Ivory Coast"))]
  437 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("IvoryCoa"))]
  437 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Côte d'Ivoire"))]
  437 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Cote d'Ivoire"))]
  437 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Cote d`Ivoire"))]
  437 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Cote dIvoire"))]
  439 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Burkina Faso"))]
  439 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("BurkinaF"))]
  450 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Liberia"))]
  451 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Sierra Leone"))]
  451 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("SierraLe"))]
  452 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Ghana"))]
  461 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Togo"))]
  471 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Cameroon"))]
  475 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Nigeria"))]
  481 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Gabon"))]
  482 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Central African Republic"))]
  482 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Central African Rep."))]
  482 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Central African Rep"))]
  482 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("CentralA"))]
  483 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Chad"))]
  484 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo"))]
  484 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, Republic of the"))]
  484 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, Republic of"))]
  484 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, Rep."))]
  484 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, Rep"))]
  484 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo-Brazzaville"))]
  484 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo (Brazzaville)"))]
  484 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, Republic of (Brazzaville)"))]
  484 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, Brazzaville"))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Democratic Republic of the Congo"))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, Democratic Republic of the"))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, Democratic Republic"))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, Dem. Rep. of"))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, Dem. Rep."))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo-Kinshasa"))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo (Kinshasa)"))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, Democratic Republic of (Kinshasa)"))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo, DR"))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("DEM. REP. CONGO"))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Congo-Zaire"))]
  490 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Zaire"))]
  500 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Uganda"))]
  501 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Kenya"))]
  510 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Tanzania"))]
  511 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Zanzibar"))]
  516 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Burundi"))]
  517 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Rwanda"))]
  520 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Somalia"))]
  522 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Djibouti"))]
  530 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Ethiopia"))]
  531 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Eritrea"))]
  540 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Angola"))]
  541 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Mozambique"))]
  551 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Zambia"))]
  552 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Zimbabwe"))]
  553 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Malawi"))]
  560 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("South Africa"))]
  560 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("SouthAfr"))]
  565 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Namibia"))]
  570 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Lesotho"))]
  571 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Botswana"))]
  572 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Swaziland"))]
  572 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Swazilan"))]
  580 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Madagascar"))]
  580 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Madagasc"))]
  581 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Comoros"))]
  590 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Mauritius"))]
  590 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Mauritiu"))]
  591 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Seychelles"))]
  600 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Morocco"))]
  600 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Morocco/Western Sahara"))]
  615 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Algeria"))]
  616 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Tunisia"))]
  620 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Libya"))]
  625 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Sudan"))]
  630 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Iran"))]
  630 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Iran, Islamic Republic"))]
  630 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Iran, Ismalic Rep."))]
  630 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Iran, Ismalic Rep"))]
  640 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Turkey"))]
  645 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Iraq"))]
  651 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Egypt"))]
  651 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Egypt, Arab Republic"))]
  651 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Egypt, Arab Rep."))]
  652 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Syria"))]
  652 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Syrian Arab Republic"))]
  660 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Lebanon"))]
  663 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Jordan"))]
  666 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Israel"))]
  670 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Saudi Arabia"))]
  670 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("SaudiAra"))]
  678 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen")) & year<=1990]
  678 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen AR"))]
  679 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen")) & year>=1990]
  678 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen Arab Republic"))]
  678 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("YEMEN ARAB REP."))]
  678 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("North Yemen"))]
  678 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen, North"))]
  
  679 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen, Rep.")) & year<=1990]
  679 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen, Republic of"))& year<=1990]
  
  
  679 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen, Rep."))& year>=1990]
  679 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen, Republic of"))& year>=1990]
  
  680 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen People's Republic"))]
  680 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen PR"))]
  680 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("South Yemen"))]
  680 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Yemen, South"))]
  680 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("YEMEN PEOP. REP."))]
  690 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Kuwait"))]
  692 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Bahrain"))]
  694 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Qatar"))]
  696 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("United Arab Emirates"))]
  696 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("U. ARAB EMIRATES"))]
  
  700 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Afghanistan"))]
  701 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Turkmenistan"))]
  702 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Tajikistan"))]
  703 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Kyrgyzstan"))]
  703 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Kyrgyz Republic"))]
  704 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Uzbekistan"))]
  705 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Kazakhstan"))]
  710 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("China"))]
  710 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("China, People's Republic"))]
  710 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("China, People's Rep."))]
  710 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("China, People's Rep"))]
  710 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("China, PRC"))]
  710 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("China (P.R.C.)"))]
  710 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("China,P.R.: Mainland"))]
  712 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Mongolia"))]
  713 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Taiwan"))]
  713 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Taiwan, China"))]
  713 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("China (Taiwan)"))]
  730 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Korea"))]
  731 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("North Korea"))]
  731 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Korea, North"))]
  731 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("KOREA, N."))]
  731 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Korea, Democratic Republic"))]
  731 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Korea, Dem. Rep."))]
  732 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("South Korea"))]
  732 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("KOREA, S."))]
  732 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Korea, South"))]
  732 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Korea, Republic of"))]
  732 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Republic of Korea"))]
  732 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Korea, Rep."))]
  740 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Japan"))]
  750 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("India"))]
  760 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Bhutan"))]
  770 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Pakistan"))]
  771 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Bangladesh"))]
  775 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Myanmar"))]
  775 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Burma"))]
  775 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Burma (Myanmar)"))]
  775 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Myanmar/Burma"))]
  775 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Myanmar (Burma)"))]
  780 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Sri Lanka"))]
  780 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Sri Lanka (Ceylon)"))]
  781 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Maldives"))]
  790 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Nepal"))]
  800 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Thailand"))]
  811 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Cambodia"))]
  812 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Laos"))]
  812 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Lao People's Dem.Rep"))]
  812 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Lao People's Democratic Republic"))]
  816 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Vietnam")) & year >=1975]
  816 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Viet Nam"))]
  817 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Vietnam")) & year<=1975]
  817 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Republic of Vietnam"))]
  817 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Vietnam, Republic of"))]
  820 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Malaysia"))]
  830 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Singapore"))]
  830 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Singapor"))]
  835 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Brunei"))]
  840 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Philippines"))]
  850 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Indonesia"))]
  850 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Indonesi"))]
  860 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("East Timor"))]
  860 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Timor-Leste"))]
  900 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Australia"))]
  900 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Australi"))]
  910 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Papua New Guinea"))]
  910 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("PapuaNew"))]
  910 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("PAPUA N.G."))]
  920 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("New Zealand"))]
  920 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("NewZeala"))]
  935 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Vanuatu"))]
  940 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Solomon Islands"))]
  946 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Kiribati"))]
  947 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Tuvalu"))]
  950 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Fiji"))]
  955 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Tonga"))]
  970 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Nauru"))]
  983 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Marshall Islands"))]
  986 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Palau"))]
  987 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Federated States of Micronesia"))]
  987 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Micronesia (Federated States of)"))]
  987 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Micronesia, Fed. Sts."))]
  987 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Micronesia"))]
  990 -> ccode$ccode[str_detect(ccode$cctry, ignore.case("Samoa"))]
  ccode<-cbind.data.frame(ccode$ccode, data, stringsAsFactors=FALSE)
  colnames(ccode)[1]<-"ccode"
  return(ccode)
  
}
